info:
    app:
        description: Master Spring Boot
        name: Spring Boot Master Class Course
        version: 1.0.0
    company:
        name: edu.yacoubi
management:
    endpoint:
        health:
            show-details: always
        info:
            enabled: true
    endpoints:
        web:
            base-path: /manage
            exposure:
                include: health,info,prometheus
    info:
        build:
            enabled: true
        env:
            enabled: true
        git:
            enabled: true
        java:
            enabled: true
        os:
            enabled: true
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: never
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    main:
        banner-mode: 'off'
    output:
        ansi:
            enabled: always
